### PR TITLE
Accept factory traits

### PR DESCRIPTION
**Pull request by michbert**

### CODE REVIEW

**Comment by rossmeissl** [comment]
@michbert I figured out why the tests weren't running: 9f9be8f253bdcba34794c197f816984ccd73c814

Would you please pull upstream master into your fork and add a trait test from there?

**Comment by michbert** [comment]
@rossmeissl I added two basic trait tests

btw. still getting failures when running rspec, see issue #11

**Comment by ronaldotijucas** [comment]
Hi guys, what's up?

I think that I figure out the @michbert's problem :smile: . The problem is how the tests are running.

@michbert  instead run:
```ruby
rspec
```
you need to run:
```ruby
rake spec
```
Right @rossmeissl?

For tests I changed the rake to run the seeds (48431 and 28084) and it's run perfectly.

So dudes, I hope this help us to merge this PR.

Best regards

**Comment by rossmeissl** [comment]
@ronaldotijucas thanks for investigating. Is there a change I need to make to the Rakefile to get things shipshape? If so could you please provide a diff or a PR?

Thanks!

**Comment by ronaldotijucas** [comment]
@rossmeissl, you don't need to do anything. It's already correct. But if you wish, I can put a section in the ReadMe showing how the contributors should run the specs.

**Comment by rossmeissl** [comment]
@ronaldotijucas please submit that as a separate PR — I'll merge this one in the meantime

**Pull request merged**
