### PR TITLE
namespace hangar routes to prevent conflicts with app routes

### PR DESCRIPTION
**Pull request by davidguthu**

### CODE REVIEW

**Comment by rossmeissl** [comment]
@davidguthu There shouldn't be any conflicts because of the constraint on the route. Are you seeing one?

**Comment by davidguthu** [comment]
apparently hangar is loading before the rest of our routes, and it blows up when it hits a route in our app that just happened to match the name of one of our factories. I updated a few more things, just rspec versions, etc. There is also one test that was already failing, the test that an exception is thrown when we require environment if we're not in test environment.

**Comment by rossmeissl** [comment]
@davidguthu strange, there must be an issue with new Rails or something. Will investigate.

**Comment by davidguthu** [comment]
@rossmeissl the test failed when I ran it with just master.

**Comment by rossmeissl** [comment]
@davidguthu I'm showing all tests green now. Can you please confirm?

**Comment by rossmeissl** [comment]
Closing in favor of #19 which is still WIP

@davidguthu nothing against your PR you just stopped responding to me!

**Pull request closed without merging**
